### PR TITLE
Change string length check to use codePointCount

### LINKED ISSUE #743: Unicode support: Value '👨🏿‍👩🏿‍👧🏿‍👦🏿' can't be stored to database column because exceeds length
Let say we have MySQL >= 5.0 and a column `val emoji = varchar(16)`. 

Starting from MySQL 5.0 a varchar column requires to define its size in symbols. If we consider  '👨🏿‍👩🏿‍👧🏿‍👦🏿' emoji, we found that it has 11 symbols: man emoji, skin modifier, ZWJ (zero-width joiner), woman emoji, skin modifier, ZWJ, girl emoji, skin modifier, ZWJ, boy emoji, skin modifier.

Thus, this emoji can be inserted to `val emoji = varchar(16)`. 

However, if we try to insert '👨🏿‍👩🏿‍👧🏿‍👦🏿' there via exposed, we'll get `java.lang.IllegalStateException: Value '👨🏿‍👩🏿‍👧🏿‍👦🏿' can't be stored to database column because exceeds length circlet.stickers.server.DBStickers$Sticker.symbol.columnType.colLength`

https://github.com/JetBrains/Exposed/blob/21659eab0f7cd57eaa0bfb8ee1dd4ff00f65fdd3/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/statements/UpdateBuilder.kt#L21

The reason for this behavior is that in Java `"👨🏿‍👩🏿‍👧🏿‍👦🏿".lenght == 19`, because every emoji and skin modifier is considered as a pair of symbols (https://docs.oracle.com/javase/tutorial/i18n/text/unicode.html)

### PR DESCRIPTION
**Pull request by pt2121**
Fix #743 
🤞

### CODE REVIEW

File: exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DMLTests.kt [hunk 1]
```diff
@@ -1460,6 +1461,41 @@ class DMLTests : DatabaseTestsBase() {
             )
         }
     }
+
+    // https://github.com/JetBrains/Exposed/issues/743
+    // need to configure the MySQL server with character_set_server=utf8mb4?
+    // https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-charsets.html
+    @Ignore
```
Comment (pt2121) [inline exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DMLTests.kt]: I can't get this test to work. I think we might need to need to configure the server with `character_set_server=utf8mb4`.
