### PR TITLE
Fix how changes are calculated for non-default schema table

### LINKED ISSUE #1661: Simple Table with schema fails when using SchemaUtils.createMissingTablesAndColumns
Whenever I try to use a schema it fails with a schema table, when I am going to initialize with SchemaUtils.createMissingTablesAndColumns

```
object Tests: LongIdTable("auth.test")

SchemaUtils.createSchema(Schema("auth"))

SchemaUtils.createMissingTablesAndColumns(
    listOf(Tests),
    inBatch = true,
    withLogs = true
)
```

DEBUG Exposed - CREATE TABLE IF NOT EXISTS auth.test (id BIGSERIAL PRIMARY KEY)
DEBUG Exposed - ALTER TABLE auth.test ADD id BIGSERIAL PRIMARY KEY
WARN  Exposed - Transaction attempt #0 failed: java.sql.BatchUpdateException: Batch entry 0 ALTER TABLE auth.test ADD id BIGSERIAL PRIMARY KEY was aborted: **ERROR: column "id" of relation "test" already exists**  Call getNextException to see other errors in the batch.. Statement(s): ALTER TABLE auth.test ADD id BIGSERIAL PRIMARY KEY

With that I am not able to use any database schema

### PR DESCRIPTION
**Pull request by AlexeySoshin**
Fixes #1661

### CODE REVIEW

**Comment by albert361** [comment]
Hi @AlexeySoshin Is there any progress here or when will you release the next version?

File: exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt
Comment (bog-walk) [inline exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt:1]: Could you please confirm if these changes cover the case when a schema-prefixed table has a column with an index? i.e. A case like this?

```kt
@Test
fun testCreateMissingTablesAndColumnsWithSchema() {
    val schemaName = "my_schema"
    val schema = Schema(schemaName)
    val testTable = object : IntIdTable("$schemaName.test_table") {
        val number = integer("number").uniqueIndex()
    }

    withDb(excludeSettings = listOf(TestDB.SQLITE)) {
        SchemaUtils.createSchema(schema)
        try {
            SchemaUtils.createMissingTablesAndColumns(testTable)
            assertTrue(testTable.exists())
        } finally {
            SchemaUtils.dropSchema(schema, cascade = true)
        }
    }
}
````

**Review by bog-walk — COMMENTED** [review]
@AlexeySoshin Thanks for all your contributions to the project btw.

File: exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt [hunk 1]
```diff
@@ -329,14 +334,27 @@ class Join(
...
 open class Table(name: String = "") : ColumnSet(), DdlAware {
+
+    val schema: String
+
+    init {
+        schema = if (name.contains(".")) {
+            name.substringBefore(".")
+        } else {
+            ""
+        }
```
Comment (BierDav) [inline exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt:345]: this is leaves room for possible unexpected behavior, when the table name contains multiple dots

**Review by BierDav — CHANGES_REQUESTED** [review]

File: exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt (hunk 1 above)
Comment (BierDav) [reply exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt:345]: My suggestions would be, this would treat the table name always the same:
        schema = if (name.contains(".")) {
            name.substringBeforeLast(".")
        } else {
            ""
        }

File: exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt
Comment (BierDav) [reply exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateMissingTablesAndColumnsTests.kt:1]: @AlexeySoshin would you be so nice and answer @bog-walk question?

File: exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt (hunk 1 above)
Comment (bog-walk) [reply exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt]: Thanks for the suggested changes @BierDav !

**Review by e5l — APPROVED** [review]

**Review by BierDav — APPROVED** [review]

**Comment by BierDav** [comment]
LGMT
